[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.11.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.20.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[prune]
  go-tests = true
  unused-packages = true